name: VBCoach
favicon: null
layout_spectrum: 0.3657851815223694
typography_spectrum: 0.23486002045683563
title: VB Coach
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4104889549780637
  lightness: 0.9592314476612955
  saturation: 0.003054691944271326
  rhythmicContrast: 0.2871082150377333
purpose: []
