typography_spectrum: 0.23486002045683563
color:
  brandColors:
    - '#000000'
    - '#fea167'
    - '#303c70'
    - '#7e899f'
    - '#f8f0f0'
  brandStrength: 0.4104889549780637
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.2871082150377333
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.94335
analytics:
  google: null
  facebook: null
  twitter: null
name: VBCoach
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: e29395dc-89e7-4073-904b-0bcc7b91c901
    url: 2016-07-21-recently-ive-been-reading-the-book.html
    name: 'The COMT Gene, Long Ring Fingers and Female Competitiveness'
    type: content
favicon: null
title: VB Coach
purpose: []
