name: VBCoach
favicon: null
layout_spectrum: 0.5654629615601152
typography_spectrum: 0.3507000997196883
title: VB Coach
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fea167'
    - '#303c70'
    - '#7e899f'
    - '#f8f0f0'
  brandStrength: 0.4104889549780637
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.2871082150377333
purpose: []
